# Generated by Django 5.0.6 on 2026-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.CharField(choices=[('DINAMITA', 'Dinamita'), ('FULMINANTE', 'Fulminante'), ('MECHA', 'Mecha'), ('NITRATO', 'Nitrato'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
    ]
