# Generated by Django 5.0.6 on 2026-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_tipo_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
