# Generated by Django 6.0.5 on 2026-08-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientoinventario_stock_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
