# Generated by Django 6.0.5 on 2026-09-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0005_materialorden'),
        ('inventario', '0005_insumo_numero_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='despachos.despacho'),
        ),
    ]
