# Generated by Django 5.0.6 on 2026-05-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='bodeguero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos_bodeguero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despachos.despacho'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='detalleordentiro',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='ordentiro',
            name='bodeguero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_bodeguero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentiro',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lugarconsumo'),
        ),
        migrations.AddField(
            model_name='ordentiro',
            name='perforista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_perforista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleordentiro',
            name='orden_tiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despachos.ordentiro'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='orden_tiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despachos.ordentiro'),
        ),
    ]
