# Generated by Django 5.0.6 on 2026-05-22 23:07

import despachos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentiro',
            name='cantidad_tiros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordentiro',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentiro',
            name='codigo_orden',
            field=models.CharField(default=despachos.models.generar_codigo, max_length=50, unique=True),
        ),
    ]
