# Generated by Django 5.0.6 on 2026-05-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0003_ordentiro_cantidad_tiros_ordentiro_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentiro',
            name='metros_mecha',
            field=models.DecimalField(decimal_places=2, default=1.8, max_digits=5),
        ),
    ]
