# Generated by Django 6.0.5 on 2026-06-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0004_ordentiro_metros_mecha'),
        ('inventario', '0004_movimientoinventario_stock_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('orden_tiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='despachos.ordentiro')),
            ],
        ),
    ]
