# Generated by Django 6.0.5 on 2026-09-08 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0005_materialorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='fecha_despacho',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordentiro',
            name='fecha_orden',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
