# Generated by Django 5.0.6 on 2026-05-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0003_ordentiro_cantidad_tiros_ordentiro_motivo_rechazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaPolvorin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENTREGADO', 'ENTREGADO')], default='ENTREGADO', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='despachos.despacho')),
                ('polvorinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
