# Generated by Django 5.0.6 on 2026-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polvorin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregapolvorin',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('RECHAZADO', 'RECHAZADO')], default='ENTREGADO', max_length=20),
        ),
    ]
