# Generated by Django 6.0.5 on 2026-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polvorin', '0002_alter_entregapolvorin_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregapolvorin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
